apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus"
    prometheus.io/port: "9411"
    fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
    fabric8.io/git-branch: "release-v0.1.5"
    fabric8.io/build-id: "3"
    fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
    fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
  labels:
    provider: "fabric8"
    project: "zipkin"
    version: "0.1.5"
    group: "io.fabric8.zipkin"
  name: "zipkin"
spec:
  ports:
  - port: 9411
    protocol: "TCP"
    targetPort: 9411
  selector:
    project: "zipkin"
    provider: "fabric8"
    group: "io.fabric8.zipkin"
  type: "LoadBalancer"