# Azure storage account secrets (Replica of ~/persistent-storage/azure/secrets.yaml)
#   This is required as the PVC in this databases namespace will only be able to access secrets in its own namespace (cant escape to default namespace)
apiVersion: v1
kind: Secret
metadata:
  name: tabcorpadditionalstorage-storage-account-secret
  namespace: zipkin
type: Opaque
data:
  azurestorageaccountname: dGFiY29ycGFkZGl0aW9uYWxzdG9yYWdl
  azurestorageaccountkey: ektudTEvdDlYSXZhTDRla2dJRG1uZDVwdzdpQkZsbnA1dmNCSkYvVEx6WTFpa2lMQy9zeEVJZUp5NzZlRVBDcE5yRzNlUmRHNGlXdjRNWm4wVkV4eGc9PQ==