apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/scrape: "true"
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus/src/main/fabric8/icon.png"
    fabric8.io/git-commit: "61631316443196f4367d519b9339b58abc99a097"
    fabric8.io/git-branch: "release-v2.2.259"
    fabric8.io/build-id: "1"
    fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/61631316443196f4367d519b9339b58abc99a097"
    fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/1"
  labels:
    provider: "fabric8"
    expose: "true"
    project: "prometheus"
    version: "2.2.259"
    group: "io.fabric8.devops.apps"
  name: "prometheus"
  namespace: zipkin
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 9090
  selector:
    project: "prometheus"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"