apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    provider: "fabric8"
    project: "prometheus"
    version: "2.2.259"
    group: "io.fabric8.devops.apps"
  name: "metrics"
  namespace: zipkin