apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipkin-mysql-azure-file-pvc
  namespace: "zipkin"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: zipkin-mysql-azure-file-pv