apiVersion: v1
kind: Service
metadata:
  name: zipkin-mysql
  namespace: "zipkin"
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    provider: "fabric8"
    project: "zipkin-mysql"
    group: "io.fabric8.zipkin"