apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/kafka/src/main/fabric8/icon.png"
    fabric8.io/git-commit: "500219733b1151415686940f4b893d7add206822"
    fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kafka&var-version=2.2.153"
    fabric8.io/build-id: "2"
    fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/2"
    fabric8.io/git-branch: "release-v2.2.153"
    fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/500219733b1151415686940f4b893d7add206822"
  labels:
    provider: "fabric8"
    project: "kafka"
    version: "2.2.153"
    group: "io.fabric8.ipaas.apps"
  name: "kafka"
  namespace: "zipkin"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "kafka"
      group: "io.fabric8.ipaas.apps"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "500219733b1151415686940f4b893d7add206822"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kafka&var-version=2.2.153"
        fabric8.io/build-id: "2"
        fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/2"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/kafka/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.153"
        fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/500219733b1151415686940f4b893d7add206822"
      labels:
        provider: "fabric8"
        project: "kafka"
        version: "2.2.153"
        group: "io.fabric8.ipaas.apps"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/kafka:2.2.153"
        imagePullPolicy: "IfNotPresent"
        name: "kafka"
        ports:
        - containerPort: 9092
          name: "kafka"
        - containerPort: 8778
          name: "jolokia"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: "/opt/kafka/logs"
          name: "logs"
          readOnly: false
      volumes:
      - emptyDir:
          medium: "Memory"
        name: "logs"