apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/kafka/src/main/fabric8/icon.png"
    fabric8.io/git-commit: "500219733b1151415686940f4b893d7add206822"
    fabric8.io/git-branch: "release-v2.2.153"
    fabric8.io/build-id: "2"
    fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/500219733b1151415686940f4b893d7add206822"
    fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/2"
  labels:
    provider: "fabric8"
    project: "kafka"
    version: "2.2.153"
    group: "io.fabric8.ipaas.apps"
  name: "kafka"
  namespace: "zipkin"
spec:
  ports:
  - name : "tcp"
    port: 9092
    protocol: "TCP"
    targetPort: 9092
  selector:
    project: "kafka"
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
  type: "LoadBalancer"